disabled_rules:
  - file_length
  - force_cast
  - function_body_length
  - large_tuple
  - line_length
  - nesting
  - type_body_length

opt_in_rules:
 - empty_count
 - first_where
 - overridden_super_call
 - syntactic_sugar

included:
  - Sources

closure_parameter_position:
  severity: error

colon:
  apply_to_dictionaries: false
  severity: error

identifier_name:
  min_length: 2
  excluded: # names to ignore
    - id
    - to
    - URL
    - me

control_statement:
  severity: error

empty_enum_arguments:
  severity: error

first_where:
  severity: error

for_where:
  severity: error

legacy_constructor:
  severity: error

operator_whitespace:
  severity: error

overridden_super_call:
   severity: error

redundant_string_enum_value:
  severity: error

statement_position:
  severity: error

syntactic_sugar:
  severity: error

trailing_comma:
  mandatory_comma: false
  severity: error

unused_optional_binding:
  severity: error

vertical_parameter_alignment:
  severity: error
