name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Lint the code
      run: swiftlint lint

  build-xc12:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Run tests
      run: swift test

  build-xc12_2-beta:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Select xcode
      run: sudo xcode-select -s /Applications/Xcode_12.2.app
    - name: Run tests
      run: swift test

  build-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test
